apiVersion: v2
appVersion: 0.59.1
description: Collects several related Helm charts, Grafana dashboards, and Prometheus
  rules combined with documentation and scripts to provide easy to operate end-to-end
  Kubernetes cluster monitoring with Prometheus. Depends on the existence of a Cluster
  Prometheus deployed via Prometheus Operator
home: https://github.com/prometheus-operator/kube-prometheus
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- prometheus
- monitoring
kubeVersion: '>=1.16.0-0'
maintainers:
- email: arvind.iyengar@suse.com
  name: Arvind
- email: amangeet.samra@suse.com
  name: Geet
  url: https://github.com/geethub97
name: rancher-project-monitoring
type: application
version: 0.2.0-rc3
